load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gentbl_extensions.bzl", "gentbl_cc_library")

# Generate C++ header from TableGen
gentbl_cc_library(
    name = "yuzu_lexer_gen",
    include_prefix = "yuzu/Lexer",
    strip_include_prefix = "/yuzu/lib/Lexer",
    tbl_outs = [
        (
            [
                "-gen-token-kind-decls",
            ],
            "TokenKind.h.inc",
        ),
    ],
    tblgen = "//yuzu/tools/TableGen:yuzu_tblgen",
    td_file = "//yuzu/lib/TableGen:Grammar.td",
    visibility = ["//visibility:private"],
    deps = [
        "//yuzu/lib/TableGen:yuzu_tblgen_td_files",
    ],
)

cc_library(
    name = "yuzu_lexer",
    srcs = [],
    hdrs = [
        "Lexer.h",
        "Range.h",
        "Token.h",
        "TokenKind.h",
    ],
    include_prefix = "yuzu/Lexer",
    strip_include_prefix = "/yuzu/lib/Lexer",
    visibility = [
        "//yuzu/lib:__subpackages__",
        "//yuzu/test:__subpackages__",
    ],
    deps = [
        ":yuzu_lexer_gen",
    ],
)
