load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "yuzu_util",
    srcs = [],
    hdrs = [
        "ErrorHandling.h",
    ],
    include_prefix = "yuzu/Util",
    strip_include_prefix = "/yuzu/lib/Util",
    visibility = [
        "//yuzu/lib:__subpackages__",
        "//yuzu/test:__subpackages__",
    ],
    deps = [
        "@fmt",
    ],
)
