[package]
name = "yuzu"
version = "0.0.0"
edition = "2024"

[dependencies]
yuzu_anf = { path = "../yuzu_anf" }
yuzu_ast = { path = "../yuzu_ast" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_hir = { path = "../yuzu_hir" }
yuzu_lexer = { path = "../yuzu_lexer" }
yuzu_parser = { path = "../yuzu_parser" }
yuzu_syntax = { path = "../yuzu_syntax" }
yuzu_types = { path = "../yuzu_types" }
