"""Define bazel dependencies."""

module(name = "yuzu")

# Dependencies available in BCR
bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "rules_python", version = "1.2.0")
bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "rules_java", version = "8.12.0")
bazel_dep(name = "protobuf", version = "30.1")
bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "re2", version = "2024-07-02.bcr.1")
bazel_dep(name = "abseil-cpp", version = "20250512.1")
bazel_dep(name = "or-tools", version = "9.12")
bazel_dep(name = "eigen", version = "4.0.0-20241125.bcr.2")
bazel_dep(name = "highs", version = "1.11.0")
bazel_dep(name = "pcre2", version = "10.46-DEV")
bazel_dep(name = "glpk", version = "5.0.bcr.4")
bazel_dep(name = "bliss", version = "0.73")
bazel_dep(name = "scip", version = "9.2.0.bcr.3")
bazel_dep(name = "zlib-ng", version = "2.0.7")

# LLVM
import_llvm = use_extension("//bazel:extensions.bzl", "import_llvm")

llvm_configure = use_repo_rule("@llvm-raw//utils/bazel:configure.bzl", "llvm_configure")

use_repo(
    import_llvm,
    "llvm-raw",
    "llvm_zlib",
    "llvm_zstd",
)

llvm_configure(
    name = "llvm-project",
    targets = [
        "X86",
        # The bazel dependency graph for mlir-opt fails to load (at the analysis
        # step) without the NVPTX target in this list, because mlir/test:TestGPU
        # depends on the //llvm:NVPTXCodeGen target, which is not defined unless this
        # is included. @j2kun asked the LLVM maintiners for tips on how to fix this,
        # see https://github.com/llvm/llvm-project/issues/63135
        "NVPTX",
        # Needed for Apple M1 targets, see
        # https://github.com/j2kun/mlir-tutorial/issues/11
        "AArch64",
    ],
)

# FMT
bazel_dep(name = "fmt", version = "12.0.0")

# Google Test.
bazel_dep(name = "googletest", version = "1.17.0")

# Generate compile_commands.json for VSCode syntax analysis.
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "4f28899228fb3ad0126897876f147ca15026151e",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
)
