load("@llvm-project//mlir:tblgen.bzl", "td_library")

exports_files(
    glob(["**/*.td"]),
    visibility = [
        "//yuzu/lib/Ast:__pkg__",
        "//yuzu/lib/Lexer:__pkg__",
        "//yuzu/lib/Parser:__pkg__",
    ],
)

# Define the TableGen files as a library
td_library(
    name = "yuzu_tblgen_td_files",
    srcs = glob(["**/*.td"]),
    includes = ["."],
    visibility = [
        "//yuzu/lib/Ast:__pkg__",
        "//yuzu/lib/Lexer:__pkg__",
        "//yuzu/lib/Parser:__pkg__",
    ],
    deps = [
    ],
)
