# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "CompileOptions",
    "compile",
]

@typing.final
class CompileOptions:
    @property
    def debug_tokens(self) -> builtins.bool: ...
    @property
    def debug_ast(self) -> builtins.bool: ...
    @property
    def debug_hir(self) -> builtins.bool: ...
    @property
    def debug_anf(self) -> builtins.bool: ...
    @property
    def debug_reduce(self) -> builtins.bool: ...
    @property
    def debug_substrait(self) -> builtins.bool: ...
    def __new__(cls, debug_tokens: builtins.bool = False, debug_ast: builtins.bool = False, debug_hir: builtins.bool = False, debug_anf: builtins.bool = False, debug_reduce: builtins.bool = False, debug_substrait: builtins.bool = False) -> CompileOptions: ...

def compile(source: builtins.str, options: typing.Optional[CompileOptions] = None) -> bytes:
    r"""
    Compile Yuzu source to a Substrait plan, returned as protobuf bytes.
    """

