load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "yuzu_syntax",
    srcs = [
        "Green/Green.cc",
        "Green/GreenBuilder.cc",
        "Green/GreenCache.cc",
        "Syntax.cc",
    ],
    hdrs = [
        "Green/Green.h",
        "Green/GreenBuilder.h",
        "Green/GreenCache.h",
        "Green/GreenIterator.h",
        "Syntax.h",
        "SyntaxIterator.h",
        "SyntaxKind.h",
    ],
    include_prefix = "yuzu/Syntax",
    strip_include_prefix = "/yuzu/lib/Syntax",
    visibility = [
        "//yuzu/lib/Ast:__pkg__",
        "//yuzu/test:__subpackages__",
    ],
    deps = [
        "//yuzu/lib/Util:yuzu_util",
        "@fmt",
    ],
)
