load("@rules_cc//cc:cc_library.bzl", "cc_library")

# Generate Parser code from Grammar.td
# gentbl_cc_library(
#  1
cc_library(
    name = "yuzu_parser",
    srcs = [],
    hdrs = [
        "Event.h",
        "Marker.h",
    ],
    include_prefix = "yuzu/Parser",
    strip_include_prefix = "/yuzu/lib/Parser",
    visibility = [
        "//yuzu/lib:__subpackages__",
        "//yuzu/test:__subpackages__",
    ],
    deps = [
        "//yuzu/lib/Ast:yuzu_ast",
    ],
)
