load("@rules_cc//cc:cc_library.bzl", "cc_library")

# Generate Parser code from Grammar.td
cc_library(
    name = "yuzu_parser",
    srcs = [
    ],
    hdrs = [
        "Event.h",
        "Grammar/Expr.h",
        "Grammar/Stmt.h",
        "Marker.h",
        "TokenSink.h",
        "TokenSource.h",
    ],
    include_prefix = "yuzu/Parser",
    strip_include_prefix = "/yuzu/lib/Parser",
    visibility = [
        "//yuzu/lib:__subpackages__",
        "//yuzu/test:__subpackages__",
    ],
    deps = [
        "//yuzu/lib/Ast:yuzu_ast",
        "//yuzu/lib/Lexer:yuzu_lexer",
        "//yuzu/lib/Syntax:yuzu_syntax",
    ],
)
