[package]
name = "yuzu_hir"
version = "0.0.0"
edition = "2024"

[dependencies]
id-arena = "2.3.0"

yuzu_ast = { path = "../yuzu_ast" }
yuzu_core = { path = "../yuzu_core" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_syntax = { path = "../yuzu_syntax" }
yuzu_types = { path = "../yuzu_types" }

[dev-dependencies]
yuzu_lexer = { path = "../yuzu_lexer" }
yuzu_parser = { path = "../yuzu_parser" }
expect-test = "1.5.1"
