load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gentbl_extensions.bzl", "gentbl_cc_library")

# Generate C++ header from TableGen
gentbl_cc_library(
    name = "yuzu_ast_gen",
    include_prefix = "yuzu/Ast",
    strip_include_prefix = "/yuzu/lib/Ast",
    tbl_outs = [
        (
            [
                "-gen-expr-node-decls",
            ],
            "Expr.h.inc",
        ),
        (
            [
                "-gen-syntax-kind-decls",
            ],
            "SyntaxKind.h.inc",
        ),
    ],
    tblgen = "//yuzu/tools/TableGen:yuzu_tblgen",
    td_file = "//yuzu/lib/TableGen:Grammar.td",
    visibility = ["//visibility:private"],
    deps = [
        "//yuzu/lib/Syntax:yuzu_syntax",
        "//yuzu/lib/TableGen:yuzu_tblgen_td_files",
    ],
)

cc_library(
    name = "yuzu_ast",
    srcs = [
        "Expr.cc",
    ],
    hdrs = [
        "Ast.h",
        "AstIterator.h",
        "Expr.h",
        "SyntaxKind.h",
    ],
    include_prefix = "yuzu/Ast",
    strip_include_prefix = "/yuzu/lib/Ast",
    visibility = ["//visibility:public"],
    deps = [
        ":yuzu_ast_gen",
        "//yuzu/lib/Syntax:yuzu_syntax",
    ],
)
