#include "yuzu/Ast/Ast.h"

#include <optional>

namespace yuzu::ast {

// `IdentExpr::getName()` is generated by the AST codegen from
// `Child<Ident>:$name` and returns `std::optional<Ident>`. Only
// `Ident::getName` is hand-written: its field is `Custom<String>`,
// which the codegen leaves as a declaration for us to implement by
// digging the source text out of the underlying `Identifier` token.
std::optional<StringView> Ident::getName() const {
  for (const auto &e : node.getChildrenWithTokens()) {
    if (!e.isToken()) {
      continue;
    }

    const auto token = e.getToken();
    if (token.getKind() == SyntaxKind::Identifier) {
      return token.getGreen().getSource();
    }
  }

  return std::nullopt;
}

// `mutability` is a `Custom<Mutability>` field, so the codegen leaves it for
// us: a binding is `Mutable` when the source spells `let mut`, otherwise the
// default `Immutable` (never absent, but the accessor shape is optional).
std::optional<Mutability> LetStmt::getMutability() const {
  for (const auto &e : node.getChildrenWithTokens()) {
    if (e.isToken() && e.getToken().getKind() == SyntaxKind::MutKw) {
      return Mutability::Mutable;
    }
  }
  return Mutability::Immutable;
}

} // namespace yuzu::ast
