#include "yuzu/Ast/Ast.h"

#include <optional>

namespace yuzu::ast {

// `IdentExpr::getName()` is generated by the AST codegen from
// `Child<Ident>:$name` and returns `std::optional<Ident>`. Only
// `Ident::getName` is hand-written: its field is `Custom<String>`,
// which the codegen leaves as a declaration for us to implement by
// digging the source text out of the underlying `Identifier` token.
std::optional<StringView> Ident::getName() const {
  for (const auto &e : node.getChildrenWithTokens()) {
    if (!e.isToken()) {
      continue;
    }

    const auto token = e.getToken();
    if (token.getKind() == SyntaxKind::Identifier) {
      return token.getGreen().getSource();
    }
  }

  return std::nullopt;
}

} // namespace yuzu::ast
