
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/tamiyo/.cache/JetBrains/RemoteDev/dist/16e0cd638d74a_CLion-251.23536.43/bin/cmake/linux/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.167.4-microsoft-standard-WSL2 - x86_64
...
