load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "yuzu_syntax",
    srcs = glob(
        ["**/*.cc"],
        allow_empty = True,
    ),
    hdrs = glob(["**/*.h"]),
    include_prefix = "yuzu/Syntax",
    visibility = ["//visibility:public"],
    deps = [
        "//yuzu/Util:yuzu_util",
        "@fmt",
    ],
)
