# Yuzu devcontainer zsh config.

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""            # starship handles the prompt
plugins=(git)
source $ZSH/oh-my-zsh.sh

export EDITOR=${EDITOR:-vim}

eval "$(starship init zsh)"
