[package]
name = "yuzu_plan"
version = "0.0.0"
edition = "2024"

[dependencies]
id-arena = "2.3.0"
petgraph = "0.8.3"

yuzu_anf = { path = "../yuzu_anf" }
yuzu_diagnostics = { path = "../yuzu_diagnostics" }
yuzu_core = { path = "../yuzu_core" }
yuzu_registry = { path = "../yuzu_registry" }
yuzu_types = { path = "../yuzu_types" }

[dev-dependencies]
expect-test = "1.5.1"
yuzu_ast = { path = "../yuzu_ast" }
yuzu_hir = { path = "../yuzu_hir" }
yuzu_lexer = { path = "../yuzu_lexer" }
yuzu_parser = { path = "../yuzu_parser" }
