use num_derive::{FromPrimitive, ToPrimitive};
use yuzu_lexer::token_kind::TokenKind;

#[repr(u16)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, FromPrimitive, ToPrimitive)]
pub enum SyntaxKind {
    // Tokens
    Plus,
    Minus,
    Star,
    StarStar,
    Slash,
    Eq,
    EqEq,
    Neq,
    Lt,
    Lte,
    Gt,
    Gte,
    Shl,
    Shr,
    Arrow,
    Pipe,
    Dot,
    LeftParen,
    RightParen,
    LeftCurly,
    RightCurly,
    LeftSquare,
    RightSquare,
    Comma,
    Colon,
    AndKw,
    AsKw,
    DistinctKw,
    DropKw,
    ExtendKw,
    FnKw,
    ForKw,
    FromKw,
    ImplKw,
    InKw,
    LetKw,
    MutKw,
    NotKw,
    OrKw,
    RenameKw,
    ReturnKw,
    SelectKw,
    StructKw,
    TableKw,
    TraitKw,
    WhereKw,
    Identifier,
    BoolLit,
    IntLit,
    FloatLit,
    HexLit,
    BinaryLit,
    StringLit,
    RawStringLit,
    Comment,
    Newline,
    Space,

    // Nodes
    Root,
    Ident,

    TypeAnnotation,
    NamedTypeAnnotation,
    FuncTypeAnnotation,
    FuncTypeAnnotationParams,

    TypeParam,
    TypeBound,
    TraitRef,

    Stmt,
    StructStmt,
    StructField,
    TraitStmt,
    ImplStmt,
    FuncStmt,
    FuncParam,
    TableStmt,
    BlockStmt,
    LetStmt,
    AssignStmt,
    ReturnStmt,
    ExprStmt,

    Expr,
    IdentExpr,
    CallExpr,
    ArgList,
    FieldAccessExpr,
    StructExpr,
    StructFieldInit,
    ListExpr,
    BinaryExpr,
    UnaryExpr,
    ParenExpr,

    Rel,
    FromExpr,
    SelectExpr,
    SelectItem,
    WhereExpr,
    DistinctExpr,
    DropExpr,
    RenameExpr,
    RenameItem,
    ExtendExpr,

    Literal,
    BoolLiteral,
    IntLiteral,
    FloatLiteral,
    StringLiteral,

    // Other
    Error,
}

impl From<TokenKind> for SyntaxKind {
    fn from(token_kind: TokenKind) -> Self {
        match token_kind {
            TokenKind::Plus => Self::Plus,
            TokenKind::Minus => Self::Minus,
            TokenKind::Star => Self::Star,
            TokenKind::StarStar => Self::StarStar,
            TokenKind::Slash => Self::Slash,
            TokenKind::Eq => Self::Eq,
            TokenKind::EqEq => Self::EqEq,
            TokenKind::Neq => Self::Neq,
            TokenKind::Lt => Self::Lt,
            TokenKind::Lte => Self::Lte,
            TokenKind::Gt => Self::Gt,
            TokenKind::Gte => Self::Gte,
            TokenKind::Shl => Self::Shl,
            TokenKind::Shr => Self::Shr,
            TokenKind::Arrow => Self::Arrow,
            TokenKind::Pipe => Self::Pipe,
            TokenKind::Dot => Self::Dot,
            TokenKind::LeftParen => Self::LeftParen,
            TokenKind::RightParen => Self::RightParen,
            TokenKind::LeftCurly => Self::LeftCurly,
            TokenKind::RightCurly => Self::RightCurly,
            TokenKind::LeftSquare => Self::LeftSquare,
            TokenKind::RightSquare => Self::RightSquare,
            TokenKind::Comma => Self::Comma,
            TokenKind::Colon => Self::Colon,
            TokenKind::AndKw => Self::AndKw,
            TokenKind::AsKw => Self::AsKw,
            TokenKind::DistinctKw => Self::DistinctKw,
            TokenKind::DropKw => Self::DropKw,
            TokenKind::ExtendKw => Self::ExtendKw,
            TokenKind::FnKw => Self::FnKw,
            TokenKind::ForKw => Self::ForKw,
            TokenKind::FromKw => Self::FromKw,
            TokenKind::ImplKw => Self::ImplKw,
            TokenKind::InKw => Self::InKw,
            TokenKind::LetKw => Self::LetKw,
            TokenKind::MutKw => Self::MutKw,
            TokenKind::NotKw => Self::NotKw,
            TokenKind::OrKw => Self::OrKw,
            TokenKind::RenameKw => Self::RenameKw,
            TokenKind::ReturnKw => Self::ReturnKw,
            TokenKind::SelectKw => Self::SelectKw,
            TokenKind::StructKw => Self::StructKw,
            TokenKind::TableKw => Self::TableKw,
            TokenKind::TraitKw => Self::TraitKw,
            TokenKind::WhereKw => Self::WhereKw,
            TokenKind::Identifier => Self::Identifier,
            TokenKind::BoolLit => Self::BoolLit,
            TokenKind::IntLit => Self::IntLit,
            TokenKind::FloatLit => Self::FloatLit,
            TokenKind::HexLit => Self::HexLit,
            TokenKind::BinaryLit => Self::BinaryLit,
            TokenKind::StringLit => Self::StringLit,
            TokenKind::RawStringLit => Self::RawStringLit,
            TokenKind::Comment => Self::Comment,
            TokenKind::Newline => Self::Newline,
            TokenKind::Space => Self::Space,
            TokenKind::Error => Self::Error,
        }
    }
}
